### ISSUE TITLE
Add validation messages to translation files

### ISSUE THREAD

**Issue by jansmolders86** [jansmolders86/mediacenterjs#16]
The validation messages in /app/settings/view/settings.jade and /views/setup.jade need to be added to the translation file  so the messages can be show in the native language

**Comment by ildac** [comment]
I had some free time, and I was fixing a bit the Italian translation.
Since this issue is translation related I also looked into this but I could not see which validation messages are you referring to:
- /apps/settings/view/settings.jade looks all translated to me
- /views/setup.jade here the translation labels are not implemented at all, and if is what you were referring to, I could do that

**Comment by jansmolders86** [comment]
You are right :) This issue is depricated since the settings app got changed to Angular :)
I'd love to see your Italian improvements though! I'm afraid my italian is quite limited to food and drinks ;)
