### ISSUE TITLE
Easy access to remote

### ISSUE THREAD

**Issue by hoffi** [jansmolders86/mediacenterjs#175]
Hey, 
what about a QR-Code or something to easily access the remote?
So you can easily scan the code and instantly have the remote on your smartphone instead of looking for the right URL to type in :)

Would be something for the future but just wanted to share this idea with you.

**Comment by jansmolders86** [comment]
Very, very cool idea Stefan! I love it! I'm going to think of  a nice place to put it :)

**Comment by jansmolders86** [comment]
Found an excellent plugin for generating a qr code. I'm going to use it to generate a tile image on the fly for the remote!

**Comment by jansmolders86** [comment]
Hey @hoffi , I almost was ready to merge the qrcode stuff but then I realized something. Currently I generate the qrcode client side on the fly using location.domain + location.port. but of course that won't work for your mobile phone seeing as location.domain will often just be localhost. Do you have any ideas? Should I generate the qrcode server side with IP rather than say localhost? But will that always work? I'm not sure tbh

**Comment by hoffi** [comment]
Hm yes i would say to get the IP on serverside using [os.networkinterfaces](http://nodejs.org/api/os.html#os_os_networkinterfaces) think that should work in general.

**Comment by jansmolders86** [comment]
I've publish the branch (qrcode) @hoffi, You can look at it if you want. It isn't my finest hour coding wise, but its all I could mustar up time wise. It works though :)

**Comment by hoffi** [comment]
Hey @jansmolders86,
can confirm it works :)

**Comment by jansmolders86** [comment]
Will do @hoffi  :) thanks!
