### ISSUE TITLE
Should data have a detail page? 

### ISSUE THREAD

**Issue by jansmolders86** [jansmolders86/mediacenterjs#181]
So many of the competition whether its XBMC or Netflix have a detail page for tv shows, albums, movies etc to show the user a bunch of metadata.
 
Naturally these pages can look awesome but I'm wondering, do we need them?
Looks can not be the only reason to implement this of course. Take the movie app. Once we have the option to tie in for instance Netflix to the app, I think a detail page could become useful because you will see movies you know nothing about. Currently though, you'll know what movies you have in your own catalog so it seems redundant. 

I'd love to hear your thoughts though!

**Comment by hoffi** [comment]
Hm interesting question..
I personally don't really look at most of these metadata, as it just don't interests me, especially for local data. 
But, as you have said, for other sources like Netflix, Spotify, etc. this would be more interesting, because i use them also for discovery. So informations like ratings, descriptions, trailer, similar movies/songs, etc. would be good to see.

Maybe it would be a good compromise to not really have a "detail page" but more a "detail overlay" or something?
I am thinking about to hover a movie/track/show and the item expands on the right or left and shows additional informations?
Do you understand what i mean and what do you think about this?

**Comment by Jon889** [comment]
Detail pages would be useful for seeing things like the plot (without scrolling text), the actors who star in it and links to sites like IMDB etc.

**Comment by hoffi** [comment]
But do you look at these infos for your local movies?

**Comment by jansmolders86** [comment]
Nope, I guess not. For me,  only when we combine cloud and local, this would become a desired feature :) 

But maybe others might find it useful to see details of their local movies. XBMC has always done it of instance.
