### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by maherbeg** [jansmolders86/mediacenterjs#62]
Could chrome cast support be implemented into the server? It'd be great to have a node based media center app that could cast to the Chromecast.

I have some example code of on the fly transcoding of mkvs at maherbeg/mkvcast The settings I've chosen only work for h264 files, but it does mean there is no drop in video quality and not much CPU usage involved as well.

**Comment by tracker1** [comment]
I'd had similar thoughts... where the "remote" would be a web-app (react), that would then update what was being displayed on the chromecast device(s).  Had also thought it would be cool to support multiple chromecasts...

My thinking was this way I could use my relatively beefy desktop to support playback to the chromecasts in my home, instead of having a separate htpc necessary.

I think there's room for a lot of reuse with this project, but would likely need to be a separate project as the design construct would be relatively different.

**Comment by leocaseiro** [comment]
I believe that repo should have some examples how to implement it https://github.com/googlecast/CastVideos-chrome

**Comment by leocaseiro** [comment]
I believe you are using videojs, so here we go:

https://github.com/benjipott/video.js-chromecast
https://github.com/jgubman/videojs-airplay

**Comment by jansmolders86** [comment]
While those plugins are a really amazing find and I thank you for them, I want to use it the other way around :) I want user to be able to cast a video to the media center. So in other words it has to act as a server, not a client

**Comment by mmarquezs** [comment]
So you want to be able from your phone or similar cast to the mediacenter.
Google doesn't want that, it used to be possible but then they changed the api so people couldn't do that. Nowadays unless something changed the only way I think was cloning an existing chromecast or similar. But honestly I haven't recently looked into it, but the last time i checked that was all I found.

**Comment by jansmolders86** [comment]
Yes, Sadly you're right, when this item started it was still possible. But unless Google changes there API, this one is dead in the water.

**Comment by tracker1** [comment]
@jansmolders86 It's pretty sad, especially since some newer TVs support chromecast directly... my guess it's about DMCA, and Google needs to not support streaming to disk work around to placate to various content providers.
